package com.example.model.tools

enum class Status(val value : String) {
    OK("OK"),
    TECHNICALERROR("KO - TECHNICAL ERROR"),
    SESSIONINVALID("KO - SESSION INVALID"),
    SESSIONEXPIRED("KO - SESSION EXPIRED"),
    WRONGCREDENTIALS("KO - WRONG CREDENTIALS"),
    //BADLOCATIONFORMAT("KO - BAD LOCATION FORMAT"), // a utiliser
    TOOFAST("KO  - TOO FAST"),
    BADPICKAXE("KO  - BAD PICKAXE"),
    OUTOFBOUNDS("KO - OUT OF BOUNDS"),
    //UNKNOWNID("KO - UNKNOWN ID"), // a utiliser
    NOITEMS("KO - NO ITEMS"),
    NOMONEY("KO - NO MONEY")
}